apiVersion: ec2.aws.upbound.io/v1beta1
kind: ManagedPrefixList
metadata:
  annotations:
    meta.upbound.io/example-id: ec2/v1beta1/managedprefixlist
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    addressFamily: IPv4
    entry:
    - cidr: ${aws_vpc.example.cidr_block}
      description: Primary
    - cidr: ${aws_vpc_ipv4_cidr_block_association.example.cidr_block}
      description: Secondary
    maxEntries: 5
    name: All VPC CIDR-s
    region: us-west-1
    tags:
      Env: live

---

