apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPCEndpointRouteTableAssociation
metadata:
  annotations:
    meta.upbound.io/example-id: ec2/v1beta1/vpcendpointroutetableassociation
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    region: us-west-1
    routeTableId: ${aws_route_table.example.id}
    vpcEndpointIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

