name: End to End Testing

on:
  issue_comment:
    types: [created]

jobs:
  e2e:
    # https://github.com/upbound/uptest/pull/135
    uses: iainlane/uptest/.github/workflows/pr-comment-trigger.yml@b1cf74fba3d99e624ed71ccf91334e2df9d20a4f
    secrets:
      UPTEST_CLOUD_CREDENTIALS: ${{ secrets.UPTEST_CLOUD_CREDENTIALS }}
      UPTEST_DATASOURCE: ${{ secrets.UPTEST_DATASOURCE }}
