name: Tag

on:
  workflow_dispatch: 
    inputs:
      version:
        description: 'Release version (e.g. v0.1.0)'
        required: true
      message:
        description: 'Tag message'
        required: true

jobs:
  tag:
    # https://github.com/upbound/uptest/pull/135
    uses: iainlane/uptest/.github/workflows/provider-tag.yml@b1cf74fba3d99e624ed71ccf91334e2df9d20a4f
    with:
      version: ${{ github.event.inputs.version }}
      message: ${{ github.event.inputs.message }}
